version: '2.2'
services:
  postgres:
    image: postgres:13.5
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zero
    ports:
      - 5432:5432